### ISSUE TITLE
Error message when using Java version 16

### ISSUE THREAD

**Issue by lfrancioli** [seqeralabs/xpack-dnanexus#19]
When trying to run `make dx-pack` with java v16, I'm getting `ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later is installed`. Looking into the code, it seems like versions 8 to 15 are supported but the error message suggests a different problem since 16 > 8.

**Comment by pditommaso** [comment]
Latest version allows the use of Java 16
