### ISSUE TITLE
DNAnexus app review

### ISSUE THREAD

**Issue by commandlinegirl** [seqeralabs/xpack-dnanexus#3]
Please consider the following changes to the app:

## 1. Readme.md
 
Platform users are accustomed to a specific structure of the Readme (you can check examples in the menu Tools > Tool Library):

 ```
 # Nextflow
 
 ## What does this app do?
 
 ## What are typical use cases for this app?
 
 ## What data are required for this app to run?
 
 > High-level description of required inputs. Don't have to list all the options, as dxapp.json does that already.
 
 ## What does this app output?
 
 The app produces no output.
 
 ## How does this app work?
 
 > If the app wraps another piece of software, provide a link to the documentation unless already mentioned above.
 >
 > Optionally provide a high level summary of execution steps.
``` 
 
 ## 2. dxapp.json
 
 ## name
 
 Please change the name to: 

```
"name": "nextflow",
```
App can be run and found with the "app-" prefix so we don't add an additional app- suffix.

## summary

A one-liner description of the app, it will be displayed under the app name on the Tools page, for example:

"Runs Nextflow pipeline on DNAnexus"

 ## inputSpec
 
 For each item add the following fields:
 
 * help (Short description of what the field intakes, should end with a dot)
 * label (start with capital letter, e.g. Pipeline URL, License, Working directory, Resume ID, Log file, etc. so that it displays nicely in the UI)
 
 ## runSpec
 
 Please set release to "20.04" and add field "version" set to "0" (string) for an up-to-date app execution environment.

 ## regionalOptions
 
 Please add the remaining regions:
 
 ```
     "aws:eu-central-1": {
       "systemRequirements": {
         "*": {
           "instanceType": "mem1_ssd1_v2_x2"
         }
       }
     },
     "aws:cn-north-1": {
       "systemRequirements": {
         "*": {
           "instanceType": "mem1_ssd1_v2_x2"
         }
       }
     },
     "aws:ap-southeast-2": {
       "systemRequirements": {
         "*": {
           "instanceType": "mem1_ssd1_v2_x2"
         }
       }
     },
     "azure:westeurope": {
       "systemRequirements": {
         "*": {
           "instanceType": "azure:mem2_ssd1_x2"
         }
       }
     },
     "azure:westus": {
       "systemRequirements": {
         "*": {
           "instanceType": "azure:mem2_ssd1_x2"
         }
       }
     },
 ```
 
 Add the following fields:
 
 ## details
 
Add information about the license of the Nextflow tool and whatsNew, you can follow the example:
 
   "details": {
     "upstreamProjects": [
       {
         "name": "Nextflow",
         "repoUrl": "https://github.com/...",
         "version": "...",
         "license": "...",
         "licenseUrl": "https://github.com/.../LICENSE.txt",
         "author": "..."
       }
     ],
     "citations": [
       "..."
     ],
     "whatsNew": "* 1.0.0: First version of the app"
   },
 
 ### billTo
 
   "billTo": "org-nextflow..?"
 
 ### ignoreReuse
 
   "ignoreReuse": "true"
 
 # 3. dxapp.sh
 
 1. Please move "dxapp.sh" to an `src/ folder` and change runSpec.file in dxapp.json to "src/dxapp.sh"
 
 2. `nf_task_entry` and `nf_task_exit` are not used in this file so can they be removed?

**Comment by DNxEnterprise** [comment]
@commandlinegirl  Thanks.

"billTo" should be "org-seqera"

**Comment by pditommaso** [comment]
> "billTo" should be "org-seqera"

Would this imply that we'll people for people using this app?

**Comment by pditommaso** [comment]
> Please move "dxapp.sh" to an src/ folder and change runSpec.file in dxapp.json to "src/dxapp.sh"

Done f9ac927 ✅

**Comment by pditommaso** [comment]
> Please add the remaining regions:

Done 627f13c ✅

**Comment by pditommaso** [comment]
> Add information about the license of the Nextflow tool and whatsNew,

Done ca8cb32 ✅

**Comment by pditommaso** [comment]
> A one-liner description of the app, it will be displayed under the app name on the Tools page

Done cd35d8f ✅

**Comment by pditommaso** [comment]
> Platform users are accustomed to a specific structure of the Readme

Done e138305 ✅

**Comment by pditommaso** [comment]
> Please set release to "20.04" and add field "version" set to "0"

Done 878dfb5 ✅ 

>  Please change the name to nextflow 

Done f7bdd21 ✅ 

> Add billTo 

Done e889474 ✅

**Comment by pditommaso** [comment]
> Input spec

Done 09ea2cf ✅
