### ISSUE TITLE
Support Private Github Repos as the source of Nextflow pipelines

### ISSUE THREAD

**Issue by XingGemini** [seqeralabs/xpack-dnanexus#7]
Support Private Github Repos as the source of Nextflow pipelines

Users can provide a configuration file as an input for the Nextflow app.  The configuration file can be in the JSON format and stored in a user's private project, e.g.,
```
{
    "scriptrepo": {
      "repo": "github",
      "username": "<YOUR_GIT_USERNAME>",
      "token": "<YOUR_GIT_TOKEN>",
    },
   "license": <YOUR NEXTFLOW APP LICENSE KEY>
 }
```

Similar configuration/credential file used in CWIC.
https://documentation.dnanexus.com/developer/cloud-workstations/cwic#creating-a-credentials-file

**Comment by pditommaso** [comment]
Solved cbd51aa.
